[package]
name = "swarm-test-timetable"
version = "0.1.0"
authors = ["mgr-inz-rafal <rchabowski@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.93.0"
rand = "0.6.5"
chrono = "*"
time = "*"
swarm = { path = "../swarm" }
